### ISSUE TITLE
missing main.js and App.vue files

### ISSUE THREAD

**Issue by realrecordzLab** [awardx/vue-extension-mv3-hot-reload#2]
I'm testing you package but I've noticed that `main.js` file and `App.vue` files are missing and it will use vue 2 instead of the most recent vue 3.
Did the build created using `npm run build` will work without having these two files?

**Comment by awardx** [comment]
`main.js` and `App.vue` or however you'd like to name them, can be added according to your requirements. 

With regards to version of the vue, feel free upgrading this project package to the latest Webpack version in order to upgrade vue.
