### ISSUE TITLE
Not able to make an API call as it is giving error of content_security_policy

### ISSUE THREAD

**Issue by himanshush200599** [awardx/vue-extension-mv3-hot-reload#5]
```
This is what i am getting when making a API call from one of my mixin on button click -> 
Refused to connect to <<API_END_POINT>> because it violates the following Content Security Policy directive: "connect-src ws://localhost:9090/".
```

Here is my content_security_policy in manifest file --> 
`"content_security_policy": { "extension_pages": "default-src 'self'; style-src 'self' 'unsafe-inline'" }`

Can somebody please help me in this ?
I have reached till this point from migration v2 to v3.

**Comment by himanshush200599** [comment]
how to make sure , it should be able to connect to external server without specify each URL in CSP, which is the case currently.

**Comment by himanshush200599** [comment]
Hi @awardx , if you have any input please let me know about this.
thanks

**Comment by awardx** [comment]
You should be able to make API calls from the service worker (background.js) using fetch() API
